version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8891:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:latest
    ports:
      - "33080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market
      MYSQL_INITDB_SQL: /docker-entrypoint-initdb.d/init.sql  # Specify the initialization script
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script

volumes:
  db_data:
